/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PregnantEvent {
    date: Time;
    eventType: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ANCVisit {
    visitNumber: bigint;
    date?: Time;
    completed: boolean;
    notes?: string;
}
export interface GrowthMeasurement {
    weight?: number;
    height?: number;
    measurementId: string;
    timestamp: bigint;
    headCircumference?: number;
}
export interface Post {
    id: string;
    title: string;
    content: string;
    author: string;
    timestamp: bigint;
    replies: Array<Post>;
    category: PostCategory;
    authorPrincipal: Principal;
}
export interface ImmunizationRecord {
    vaccine: string;
    date?: Time;
    completed: boolean;
}
export interface UserProfile {
    age: bigint;
    country: string;
    expectedDueDate?: Time;
    name: string;
    role: UserRole;
    childDob?: Time;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Languages {
    hindi = "hindi",
    nepali = "nepali",
    english = "english"
}
export enum PostCategory {
    newborn = "newborn",
    toddler = "toddler",
    vaccination = "vaccination",
    feeding = "feeding",
    mentalHealth = "mentalHealth",
    pregnancy = "pregnancy"
}
export enum UserRole {
    healthWorker = "healthWorker",
    familyMember = "familyMember",
    mother = "mother",
    pregnantWoman = "pregnantWoman"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    /**
     * / Retrieve ANC visits for the calling user.
     */
    getANCVisits(): Promise<Array<ANCVisit>>;
    /**
     * / Admin helper: retrieve ANC visits for any user.
     */
    getANCVisitsForUser(user: Principal): Promise<Array<ANCVisit>>;
    /**
     * / -----------------------------------------------------------------------
     * / Required Profile Interface (getCallerUserProfile, saveCallerUserProfile,
     * / getUserProfile)
     * / -----------------------------------------------------------------------
     * / Get the profile of the calling user.
     */
    getCallerUserProfile(): Promise<UserProfile | null>;
    /**
     * / Persistent Blob Storage
     */
    getCallerUserRole(): Promise<UserRole__1>;
    /**
     * / Retrieve immunization records for the calling user.
     */
    getImmunizations(): Promise<Array<ImmunizationRecord>>;
    /**
     * / Admin helper: retrieve immunization records for any user.
     */
    getImmunizationsForUser(user: Principal): Promise<Array<ImmunizationRecord>>;
    /**
     * / Retrieve growth measurements for the calling user.
     */
    getMeasurements(): Promise<Array<GrowthMeasurement>>;
    /**
     * / Admin helper: retrieve growth measurements for any user.
     */
    getMeasurementsForUser(user: Principal): Promise<Array<GrowthMeasurement>>;
    /**
     * / Retrieve localised page content. Available to everyone.
     */
    getPageContent(path: string, language: Languages): Promise<string | null>;
    /**
     * / Retrieve a single post by id. Available to everyone.
     */
    getPost(id: string): Promise<Post | null>;
    /**
     * / Retrieve pregnancy events for the calling user.
     */
    getPregnantEvents(): Promise<Array<PregnantEvent>>;
    /**
     * / Admin helper: retrieve pregnancy events for any user.
     */
    getPregnantEventsForUser(user: Principal): Promise<Array<PregnantEvent>>;
    /**
     * / Retrieve total visitor count. Available to everyone.
     */
    getTotalVisitors(): Promise<bigint>;
    /**
     * / Get the profile of any user. Callers may only view their own profile
     * / unless they are an admin.
     */
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / -----------------------------------------------------------------------
     * / Visitor / Analytics Stats
     * / -----------------------------------------------------------------------
     * / Record a visit. Any caller (including guests / anonymous) may call this.
     * / No sensitive data is written; only aggregate counters are updated.
     */
    recordVisit(): Promise<void>;
    /**
     * / -----------------------------------------------------------------------
     * / ANC Visit Management
     * / -----------------------------------------------------------------------
     * / Log an ANC visit for the calling user only.
     */
    saveANCVisit(visit: ANCVisit): Promise<void>;
    /**
     * / Save/update the profile of the calling user.
     */
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    /**
     * / -----------------------------------------------------------------------
     * / Immunization Records
     * / -----------------------------------------------------------------------
     * / Log an immunization record for the calling user's child.
     */
    saveImmunization(record: ImmunizationRecord): Promise<void>;
    /**
     * / -----------------------------------------------------------------------
     * / Growth Measurement Management
     * / -----------------------------------------------------------------------
     * / Save a growth measurement for the calling user's child.
     */
    saveMeasurement(record: GrowthMeasurement): Promise<void>;
    /**
     * / -----------------------------------------------------------------------
     * / General Content Management (admin-only writes)
     * / -----------------------------------------------------------------------
     * / Save localised page content. Only admins may update content.
     */
    savePageContent(path: string, content: string, language: Languages): Promise<void>;
    /**
     * / -----------------------------------------------------------------------
     * / Community Posts
     * / -----------------------------------------------------------------------
     * / Create or update a post. Users may only modify their own posts;
     * / admins may modify any post.
     */
    savePost(id: string, post: Post): Promise<void>;
    /**
     * / -----------------------------------------------------------------------
     * / Pregnancy Event Management
     * / -----------------------------------------------------------------------
     * / Log a pregnancy event for the calling user only.
     */
    savePregnantEvent(event: PregnantEvent): Promise<void>;
}
import type { ANCVisit as _ANCVisit, GrowthMeasurement as _GrowthMeasurement, ImmunizationRecord as _ImmunizationRecord, Languages as _Languages, Post as _Post, PostCategory as _PostCategory, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getANCVisits(): Promise<Array<ANCVisit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getANCVisits();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getANCVisits();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getANCVisitsForUser(arg0: Principal): Promise<Array<ANCVisit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getANCVisitsForUser(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getANCVisitsForUser(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getImmunizations(): Promise<Array<ImmunizationRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getImmunizations();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImmunizations();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getImmunizationsForUser(arg0: Principal): Promise<Array<ImmunizationRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getImmunizationsForUser(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImmunizationsForUser(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMeasurements(): Promise<Array<GrowthMeasurement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMeasurements();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMeasurements();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMeasurementsForUser(arg0: Principal): Promise<Array<GrowthMeasurement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMeasurementsForUser(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMeasurementsForUser(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPageContent(arg0: string, arg1: Languages): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPageContent(arg0, to_candid_Languages_n29(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPageContent(arg0, to_candid_Languages_n29(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPost(arg0: string): Promise<Post | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPregnantEvents(): Promise<Array<PregnantEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPregnantEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPregnantEvents();
            return result;
        }
    }
    async getPregnantEventsForUser(arg0: Principal): Promise<Array<PregnantEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPregnantEventsForUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPregnantEventsForUser(arg0);
            return result;
        }
    }
    async getTotalVisitors(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalVisitors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalVisitors();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordVisit(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordVisit();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordVisit();
            return result;
        }
    }
    async saveANCVisit(arg0: ANCVisit): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveANCVisit(to_candid_ANCVisit_n37(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveANCVisit(to_candid_ANCVisit_n37(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveImmunization(arg0: ImmunizationRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveImmunization(to_candid_ImmunizationRecord_n43(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveImmunization(to_candid_ImmunizationRecord_n43(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveMeasurement(arg0: GrowthMeasurement): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMeasurement(to_candid_GrowthMeasurement_n45(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMeasurement(to_candid_GrowthMeasurement_n45(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async savePageContent(arg0: string, arg1: string, arg2: Languages): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePageContent(arg0, arg1, to_candid_Languages_n29(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePageContent(arg0, arg1, to_candid_Languages_n29(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async savePost(arg0: string, arg1: Post): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePost(arg0, to_candid_Post_n47(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePost(arg0, to_candid_Post_n47(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async savePregnantEvent(arg0: PregnantEvent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePregnantEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePregnantEvent(arg0);
            return result;
        }
    }
}
function from_candid_ANCVisit_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ANCVisit): ANCVisit {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_GrowthMeasurement_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GrowthMeasurement): GrowthMeasurement {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_ImmunizationRecord_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmunizationRecord): ImmunizationRecord {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_PostCategory_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostCategory): PostCategory {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Post_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Post {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Post]): Post | null {
    return value.length === 0 ? null : from_candid_Post_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    visitNumber: bigint;
    date: [] | [_Time];
    completed: boolean;
    notes: [] | [string];
}): {
    visitNumber: bigint;
    date?: Time;
    completed: boolean;
    notes?: string;
} {
    return {
        visitNumber: value.visitNumber,
        date: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.date)),
        completed: value.completed,
        notes: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.notes))
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    country: string;
    expectedDueDate: [] | [_Time];
    name: string;
    role: _UserRole;
    childDob: [] | [_Time];
}): {
    age: bigint;
    country: string;
    expectedDueDate?: Time;
    name: string;
    role: UserRole;
    childDob?: Time;
} {
    return {
        age: value.age,
        country: value.country,
        expectedDueDate: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.expectedDueDate)),
        name: value.name,
        role: from_candid_UserRole_n18(_uploadFile, _downloadFile, value.role),
        childDob: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.childDob))
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vaccine: string;
    date: [] | [_Time];
    completed: boolean;
}): {
    vaccine: string;
    date?: Time;
    completed: boolean;
} {
    return {
        vaccine: value.vaccine,
        date: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.date)),
        completed: value.completed
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: [] | [number];
    height: [] | [number];
    measurementId: string;
    timestamp: bigint;
    headCircumference: [] | [number];
}): {
    weight?: number;
    height?: number;
    measurementId: string;
    timestamp: bigint;
    headCircumference?: number;
} {
    return {
        weight: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.weight)),
        height: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.height)),
        measurementId: value.measurementId,
        timestamp: value.timestamp,
        headCircumference: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.headCircumference))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    author: string;
    timestamp: bigint;
    replies: Array<_Post>;
    category: _PostCategory;
    authorPrincipal: Principal;
}): {
    id: string;
    title: string;
    content: string;
    author: string;
    timestamp: bigint;
    replies: Array<Post>;
    category: PostCategory;
    authorPrincipal: Principal;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        author: value.author,
        timestamp: value.timestamp,
        replies: from_candid_vec_n34(_uploadFile, _downloadFile, value.replies),
        category: from_candid_PostCategory_n35(_uploadFile, _downloadFile, value.category),
        authorPrincipal: value.authorPrincipal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    healthWorker: null;
} | {
    familyMember: null;
} | {
    mother: null;
} | {
    pregnantWoman: null;
}): UserRole {
    return "healthWorker" in value ? UserRole.healthWorker : "familyMember" in value ? UserRole.familyMember : "mother" in value ? UserRole.mother : "pregnantWoman" in value ? UserRole.pregnantWoman : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    newborn: null;
} | {
    toddler: null;
} | {
    vaccination: null;
} | {
    feeding: null;
} | {
    mentalHealth: null;
} | {
    pregnancy: null;
}): PostCategory {
    return "newborn" in value ? PostCategory.newborn : "toddler" in value ? PostCategory.toddler : "vaccination" in value ? PostCategory.vaccination : "feeding" in value ? PostCategory.feeding : "mentalHealth" in value ? PostCategory.mentalHealth : "pregnancy" in value ? PostCategory.pregnancy : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ANCVisit>): Array<ANCVisit> {
    return value.map((x)=>from_candid_ANCVisit_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ImmunizationRecord>): Array<ImmunizationRecord> {
    return value.map((x)=>from_candid_ImmunizationRecord_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GrowthMeasurement>): Array<GrowthMeasurement> {
    return value.map((x)=>from_candid_GrowthMeasurement_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Array<Post> {
    return value.map((x)=>from_candid_Post_n32(_uploadFile, _downloadFile, x));
}
function to_candid_ANCVisit_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ANCVisit): _ANCVisit {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_GrowthMeasurement_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GrowthMeasurement): _GrowthMeasurement {
    return to_candid_record_n46(_uploadFile, _downloadFile, value);
}
function to_candid_ImmunizationRecord_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImmunizationRecord): _ImmunizationRecord {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_Languages_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Languages): _Languages {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_PostCategory_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostCategory): _PostCategory {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_Post_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Post): _Post {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    visitNumber: bigint;
    date?: Time;
    completed: boolean;
    notes?: string;
}): {
    visitNumber: bigint;
    date: [] | [_Time];
    completed: boolean;
    notes: [] | [string];
} {
    return {
        visitNumber: value.visitNumber,
        date: value.date ? candid_some(value.date) : candid_none(),
        completed: value.completed,
        notes: value.notes ? candid_some(value.notes) : candid_none()
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    country: string;
    expectedDueDate?: Time;
    name: string;
    role: UserRole;
    childDob?: Time;
}): {
    age: bigint;
    country: string;
    expectedDueDate: [] | [_Time];
    name: string;
    role: _UserRole;
    childDob: [] | [_Time];
} {
    return {
        age: value.age,
        country: value.country,
        expectedDueDate: value.expectedDueDate ? candid_some(value.expectedDueDate) : candid_none(),
        name: value.name,
        role: to_candid_UserRole_n41(_uploadFile, _downloadFile, value.role),
        childDob: value.childDob ? candid_some(value.childDob) : candid_none()
    };
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vaccine: string;
    date?: Time;
    completed: boolean;
}): {
    vaccine: string;
    date: [] | [_Time];
    completed: boolean;
} {
    return {
        vaccine: value.vaccine,
        date: value.date ? candid_some(value.date) : candid_none(),
        completed: value.completed
    };
}
function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight?: number;
    height?: number;
    measurementId: string;
    timestamp: bigint;
    headCircumference?: number;
}): {
    weight: [] | [number];
    height: [] | [number];
    measurementId: string;
    timestamp: bigint;
    headCircumference: [] | [number];
} {
    return {
        weight: value.weight ? candid_some(value.weight) : candid_none(),
        height: value.height ? candid_some(value.height) : candid_none(),
        measurementId: value.measurementId,
        timestamp: value.timestamp,
        headCircumference: value.headCircumference ? candid_some(value.headCircumference) : candid_none()
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    author: string;
    timestamp: bigint;
    replies: Array<Post>;
    category: PostCategory;
    authorPrincipal: Principal;
}): {
    id: string;
    title: string;
    content: string;
    author: string;
    timestamp: bigint;
    replies: Array<_Post>;
    category: _PostCategory;
    authorPrincipal: Principal;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        author: value.author,
        timestamp: value.timestamp,
        replies: to_candid_vec_n49(_uploadFile, _downloadFile, value.replies),
        category: to_candid_PostCategory_n50(_uploadFile, _downloadFile, value.category),
        authorPrincipal: value.authorPrincipal
    };
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Languages): {
    hindi: null;
} | {
    nepali: null;
} | {
    english: null;
} {
    return value == Languages.hindi ? {
        hindi: null
    } : value == Languages.nepali ? {
        nepali: null
    } : value == Languages.english ? {
        english: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    healthWorker: null;
} | {
    familyMember: null;
} | {
    mother: null;
} | {
    pregnantWoman: null;
} {
    return value == UserRole.healthWorker ? {
        healthWorker: null
    } : value == UserRole.familyMember ? {
        familyMember: null
    } : value == UserRole.mother ? {
        mother: null
    } : value == UserRole.pregnantWoman ? {
        pregnantWoman: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostCategory): {
    newborn: null;
} | {
    toddler: null;
} | {
    vaccination: null;
} | {
    feeding: null;
} | {
    mentalHealth: null;
} | {
    pregnancy: null;
} {
    return value == PostCategory.newborn ? {
        newborn: null
    } : value == PostCategory.toddler ? {
        toddler: null
    } : value == PostCategory.vaccination ? {
        vaccination: null
    } : value == PostCategory.feeding ? {
        feeding: null
    } : value == PostCategory.mentalHealth ? {
        mentalHealth: null
    } : value == PostCategory.pregnancy ? {
        pregnancy: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Post>): Array<_Post> {
    return value.map((x)=>to_candid_Post_n47(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
