/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Post = IDL.Rec();
export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ANCVisit = IDL.Record({
  'visitNumber' : IDL.Nat,
  'date' : IDL.Opt(Time),
  'completed' : IDL.Bool,
  'notes' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'healthWorker' : IDL.Null,
  'familyMember' : IDL.Null,
  'mother' : IDL.Null,
  'pregnantWoman' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'country' : IDL.Text,
  'expectedDueDate' : IDL.Opt(Time),
  'name' : IDL.Text,
  'role' : UserRole,
  'childDob' : IDL.Opt(Time),
});
export const ImmunizationRecord = IDL.Record({
  'vaccine' : IDL.Text,
  'date' : IDL.Opt(Time),
  'completed' : IDL.Bool,
});
export const GrowthMeasurement = IDL.Record({
  'weight' : IDL.Opt(IDL.Float64),
  'height' : IDL.Opt(IDL.Float64),
  'measurementId' : IDL.Text,
  'timestamp' : IDL.Int,
  'headCircumference' : IDL.Opt(IDL.Float64),
});
export const Languages = IDL.Variant({
  'hindi' : IDL.Null,
  'nepali' : IDL.Null,
  'english' : IDL.Null,
});
export const PostCategory = IDL.Variant({
  'newborn' : IDL.Null,
  'toddler' : IDL.Null,
  'vaccination' : IDL.Null,
  'feeding' : IDL.Null,
  'mentalHealth' : IDL.Null,
  'pregnancy' : IDL.Null,
});
Post.fill(
  IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : IDL.Int,
    'replies' : IDL.Vec(Post),
    'category' : PostCategory,
    'authorPrincipal' : IDL.Principal,
  })
);
export const PregnantEvent = IDL.Record({
  'date' : Time,
  'eventType' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'getANCVisits' : IDL.Func([], [IDL.Vec(ANCVisit)], ['query']),
  'getANCVisitsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ANCVisit)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getImmunizations' : IDL.Func([], [IDL.Vec(ImmunizationRecord)], ['query']),
  'getImmunizationsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ImmunizationRecord)],
      ['query'],
    ),
  'getMeasurements' : IDL.Func([], [IDL.Vec(GrowthMeasurement)], ['query']),
  'getMeasurementsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(GrowthMeasurement)],
      ['query'],
    ),
  'getPageContent' : IDL.Func(
      [IDL.Text, Languages],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getPost' : IDL.Func([IDL.Text], [IDL.Opt(Post)], ['query']),
  'getPregnantEvents' : IDL.Func([], [IDL.Vec(PregnantEvent)], ['query']),
  'getPregnantEventsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PregnantEvent)],
      ['query'],
    ),
  'getTotalVisitors' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordVisit' : IDL.Func([], [], []),
  'saveANCVisit' : IDL.Func([ANCVisit], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveImmunization' : IDL.Func([ImmunizationRecord], [], []),
  'saveMeasurement' : IDL.Func([GrowthMeasurement], [], []),
  'savePageContent' : IDL.Func([IDL.Text, IDL.Text, Languages], [], []),
  'savePost' : IDL.Func([IDL.Text, Post], [], []),
  'savePregnantEvent' : IDL.Func([PregnantEvent], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Post = IDL.Rec();
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ANCVisit = IDL.Record({
    'visitNumber' : IDL.Nat,
    'date' : IDL.Opt(Time),
    'completed' : IDL.Bool,
    'notes' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'healthWorker' : IDL.Null,
    'familyMember' : IDL.Null,
    'mother' : IDL.Null,
    'pregnantWoman' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'country' : IDL.Text,
    'expectedDueDate' : IDL.Opt(Time),
    'name' : IDL.Text,
    'role' : UserRole,
    'childDob' : IDL.Opt(Time),
  });
  const ImmunizationRecord = IDL.Record({
    'vaccine' : IDL.Text,
    'date' : IDL.Opt(Time),
    'completed' : IDL.Bool,
  });
  const GrowthMeasurement = IDL.Record({
    'weight' : IDL.Opt(IDL.Float64),
    'height' : IDL.Opt(IDL.Float64),
    'measurementId' : IDL.Text,
    'timestamp' : IDL.Int,
    'headCircumference' : IDL.Opt(IDL.Float64),
  });
  const Languages = IDL.Variant({
    'hindi' : IDL.Null,
    'nepali' : IDL.Null,
    'english' : IDL.Null,
  });
  const PostCategory = IDL.Variant({
    'newborn' : IDL.Null,
    'toddler' : IDL.Null,
    'vaccination' : IDL.Null,
    'feeding' : IDL.Null,
    'mentalHealth' : IDL.Null,
    'pregnancy' : IDL.Null,
  });
  Post.fill(
    IDL.Record({
      'id' : IDL.Text,
      'title' : IDL.Text,
      'content' : IDL.Text,
      'author' : IDL.Text,
      'timestamp' : IDL.Int,
      'replies' : IDL.Vec(Post),
      'category' : PostCategory,
      'authorPrincipal' : IDL.Principal,
    })
  );
  const PregnantEvent = IDL.Record({ 'date' : Time, 'eventType' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'getANCVisits' : IDL.Func([], [IDL.Vec(ANCVisit)], ['query']),
    'getANCVisitsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ANCVisit)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getImmunizations' : IDL.Func([], [IDL.Vec(ImmunizationRecord)], ['query']),
    'getImmunizationsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ImmunizationRecord)],
        ['query'],
      ),
    'getMeasurements' : IDL.Func([], [IDL.Vec(GrowthMeasurement)], ['query']),
    'getMeasurementsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(GrowthMeasurement)],
        ['query'],
      ),
    'getPageContent' : IDL.Func(
        [IDL.Text, Languages],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getPost' : IDL.Func([IDL.Text], [IDL.Opt(Post)], ['query']),
    'getPregnantEvents' : IDL.Func([], [IDL.Vec(PregnantEvent)], ['query']),
    'getPregnantEventsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PregnantEvent)],
        ['query'],
      ),
    'getTotalVisitors' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordVisit' : IDL.Func([], [], []),
    'saveANCVisit' : IDL.Func([ANCVisit], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveImmunization' : IDL.Func([ImmunizationRecord], [], []),
    'saveMeasurement' : IDL.Func([GrowthMeasurement], [], []),
    'savePageContent' : IDL.Func([IDL.Text, IDL.Text, Languages], [], []),
    'savePost' : IDL.Func([IDL.Text, Post], [], []),
    'savePregnantEvent' : IDL.Func([PregnantEvent], [], []),
  });
};

export const init = ({ IDL }) => { return []; };