/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ANCVisit {
  'visitNumber' : bigint,
  'date' : [] | [Time],
  'completed' : boolean,
  'notes' : [] | [string],
}
export interface GrowthMeasurement {
  'weight' : [] | [number],
  'height' : [] | [number],
  'measurementId' : string,
  'timestamp' : bigint,
  'headCircumference' : [] | [number],
}
export interface ImmunizationRecord {
  'vaccine' : string,
  'date' : [] | [Time],
  'completed' : boolean,
}
export type Languages = { 'hindi' : null } |
  { 'nepali' : null } |
  { 'english' : null };
export interface Post {
  'id' : string,
  'title' : string,
  'content' : string,
  'author' : string,
  'timestamp' : bigint,
  'replies' : Array<Post>,
  'category' : PostCategory,
  'authorPrincipal' : Principal,
}
export type PostCategory = { 'newborn' : null } |
  { 'toddler' : null } |
  { 'vaccination' : null } |
  { 'feeding' : null } |
  { 'mentalHealth' : null } |
  { 'pregnancy' : null };
export interface PregnantEvent { 'date' : Time, 'eventType' : string }
export type Time = bigint;
export interface UserProfile {
  'age' : bigint,
  'country' : string,
  'expectedDueDate' : [] | [Time],
  'name' : string,
  'role' : UserRole,
  'childDob' : [] | [Time],
}
export type UserRole = { 'healthWorker' : null } |
  { 'familyMember' : null } |
  { 'mother' : null } |
  { 'pregnantWoman' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  /**
   * / Retrieve ANC visits for the calling user.
   */
  'getANCVisits' : ActorMethod<[], Array<ANCVisit>>,
  /**
   * / Admin helper: retrieve ANC visits for any user.
   */
  'getANCVisitsForUser' : ActorMethod<[Principal], Array<ANCVisit>>,
  /**
   * / -----------------------------------------------------------------------
   * / Required Profile Interface (getCallerUserProfile, saveCallerUserProfile,
   * / getUserProfile)
   * / -----------------------------------------------------------------------
   * / Get the profile of the calling user.
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  /**
   * / Persistent Blob Storage
   */
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  /**
   * / Retrieve immunization records for the calling user.
   */
  'getImmunizations' : ActorMethod<[], Array<ImmunizationRecord>>,
  /**
   * / Admin helper: retrieve immunization records for any user.
   */
  'getImmunizationsForUser' : ActorMethod<
    [Principal],
    Array<ImmunizationRecord>
  >,
  /**
   * / Retrieve growth measurements for the calling user.
   */
  'getMeasurements' : ActorMethod<[], Array<GrowthMeasurement>>,
  /**
   * / Admin helper: retrieve growth measurements for any user.
   */
  'getMeasurementsForUser' : ActorMethod<[Principal], Array<GrowthMeasurement>>,
  /**
   * / Retrieve localised page content. Available to everyone.
   */
  'getPageContent' : ActorMethod<[string, Languages], [] | [string]>,
  /**
   * / Retrieve a single post by id. Available to everyone.
   */
  'getPost' : ActorMethod<[string], [] | [Post]>,
  /**
   * / Retrieve pregnancy events for the calling user.
   */
  'getPregnantEvents' : ActorMethod<[], Array<PregnantEvent>>,
  /**
   * / Admin helper: retrieve pregnancy events for any user.
   */
  'getPregnantEventsForUser' : ActorMethod<[Principal], Array<PregnantEvent>>,
  /**
   * / Retrieve total visitor count. Available to everyone.
   */
  'getTotalVisitors' : ActorMethod<[], bigint>,
  /**
   * / Get the profile of any user. Callers may only view their own profile
   * / unless they are an admin.
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / -----------------------------------------------------------------------
   * / Visitor / Analytics Stats
   * / -----------------------------------------------------------------------
   * / Record a visit. Any caller (including guests / anonymous) may call this.
   * / No sensitive data is written; only aggregate counters are updated.
   */
  'recordVisit' : ActorMethod<[], undefined>,
  /**
   * / -----------------------------------------------------------------------
   * / ANC Visit Management
   * / -----------------------------------------------------------------------
   * / Log an ANC visit for the calling user only.
   */
  'saveANCVisit' : ActorMethod<[ANCVisit], undefined>,
  /**
   * / Save/update the profile of the calling user.
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / -----------------------------------------------------------------------
   * / Immunization Records
   * / -----------------------------------------------------------------------
   * / Log an immunization record for the calling user's child.
   */
  'saveImmunization' : ActorMethod<[ImmunizationRecord], undefined>,
  /**
   * / -----------------------------------------------------------------------
   * / Growth Measurement Management
   * / -----------------------------------------------------------------------
   * / Save a growth measurement for the calling user's child.
   */
  'saveMeasurement' : ActorMethod<[GrowthMeasurement], undefined>,
  /**
   * / -----------------------------------------------------------------------
   * / General Content Management (admin-only writes)
   * / -----------------------------------------------------------------------
   * / Save localised page content. Only admins may update content.
   */
  'savePageContent' : ActorMethod<[string, string, Languages], undefined>,
  /**
   * / -----------------------------------------------------------------------
   * / Community Posts
   * / -----------------------------------------------------------------------
   * / Create or update a post. Users may only modify their own posts;
   * / admins may modify any post.
   */
  'savePost' : ActorMethod<[string, Post], undefined>,
  /**
   * / -----------------------------------------------------------------------
   * / Pregnancy Event Management
   * / -----------------------------------------------------------------------
   * / Log a pregnancy event for the calling user only.
   */
  'savePregnantEvent' : ActorMethod<[PregnantEvent], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];